linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - revive
    - gocognit
    - gocyclo
    - misspell

linters-settings:
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 20
